### PR TITLE
Remove the DependencyUpdateErrorProcessor

### PR DESCRIPTION
**Pull request by adiaaida**
We disabled it, and now we are removing it.

Also remove its tests

### CODE REVIEW

**Review by ChadNedzlek — APPROVED** [review]

**Review by epananth — APPROVED** [review]

**Comment by ChadNedzlek** [comment]
Check with @alexperovich, since this might break stuff, because removing a service will break the deployment.

**Review by ChadNedzlek — CHANGES_REQUESTED** [review]
We need to at least leave the shell of the service behind, which is REALLY lame. Service Fabric is painful.

**Comment by adiaaida** [comment]
LAME. Ok. I'll.... redo this

**Review by ChadNedzlek — APPROVED** [review]

**Comment by riarenas** [comment]
So is there nothing we can do to completely remove a service when we're done with it, or if we want to move it across clusters? That seems unfortunate

**Review by riarenas — APPROVED** [review]

**Comment by alexperovich** [comment]
We used to be able to remove the service completely, and we wrote code to do it, but the new deployment method prevents us from doing what we are doing. Removing a service the "new way" requires a paradigm shift in how we structure our app.

**Comment by alexperovich** [comment]
We have to stop using the "DefaultServices" node, and instead deploy each service "manually" as separate azure resources, then we can delete the old service when we want to remove them.

**Comment by riarenas** [comment]
Why don't we just do that as part of this PR?

(Sorry... I added some details about this to https://dev.azure.com/dnceng/internal/_workitems/edit/2588 so we can consider it when we have to deploy the service again in the new environment)

**Comment by adiaaida** [comment]
> We have to stop using the "DefaultServices" node, and instead deploy each service "manually" as separate azure resources, then we can delete the old service when we want to remove them.

How much work do you expect that would be Alex?

**Comment by alexperovich** [comment]
We mostly just need to rewrite the DefaultServices bit into 2 separate things. A special xml that F5 in VS uses, and an azure ARM template that the deployment uses. We then also need to write the code to delete existing services at the ARM layer when they get removed from the template, because we can't use "Complete" deployment mode. I'd say probably 2 weeksish.

**Comment by adiaaida** [comment]
I think it makes sense to do it as part of the the work that Ricardo mentioned, but not as part of this PR. Going to check in.

**Pull request merged**
