### PR TITLE
Build add location Maestro API

### PR DESCRIPTION
**Pull request by JohnTortugo**
Add API for adding the same location to all assets in a Build. This is an optimization for publishing so that we don't have to do N calls to add the same location to all N assets in a build.

### CODE REVIEW

**Comment by riarenas** [comment]
Sounds like a good improvement!! What issue is this a part of?

**Comment by JohnTortugo** [comment]
> Sounds like a good improvement!! What issue is this a part of?

I didn't add to the description but I linked the issue to the PR. Anywhere, here it is: https://github.com/dotnet/arcade/issues/5077

**Comment by riarenas** [comment]
> I didn't add to the description but I linked the issue to the PR

That would work for someone less blind than me!

**Comment by JohnTortugo** [comment]
> I think we want something slightly different: Basically just a bulk form of AddAssetLocationToAsset so that we an pass a list of assetID, location, and location type and have each asset updated. That would mean I could make a single call for the entire publishing process.

:-( . Makes sense, though.

**Pull request closed without merging**
