### PR TITLE
Allow 7 day grace period for rotation verification and allow extra settings for SQL connections

### PR DESCRIPTION
**Pull request by alexperovich**
https://github.com/dotnet/core-eng/issues/13795

### CODE REVIEW

**Review by MattGal — APPROVED** [review]
Change seems fine, is there a matching issue?

**Comment by alexperovich** [comment]
This is just directly from feedback/problems we encountered last week. I will make an issue.

**Comment by ChadNedzlek** [comment]
It seems a little weird to random add 7 days... why don't we just add 7 days to the rotation interval? I'm not 100% what this logic is doing other than saying that SQL things just don't rotate for 7 days arbitrarily after it says they should.

**Comment by alexperovich** [comment]
The deployment build has a "if secrets need rotation produce an error" part. But that fails in a bad way if something was scheduled for rotation on a Tuesday. The Monday rotation won't hit it, but the Wednesday build will fail due to secrets requiring rotation. This gives the verification part a 1 week grace period, where a "rotate if needed" command would rotate them, but a "verify that nothing needs rotation" wouldn't fail.

**Comment by alexperovich** [comment]
The 7 day thing is only done if _verifyOnly is set.

**Comment by ChadNedzlek** [comment]
Ah, that makes sense. The title confused me into thinking it was related to SQL.

**Review by ChadNedzlek — APPROVED** [review]

**Comment by alexperovich** [comment]
I will add a comment to make explain the logic a bit.

**Pull request merged**
