### PR TITLE
Delete the Pull Request branch when a PR is manually merged or closed

### PR DESCRIPTION
**Pull request by riarenas**
Delete the PR branch when we detect that the PR has been merged or abandoned.

https://github.com/dotnet/arcade/issues/3214

Validation:
Validated this with these two dependency update PRs using the scenario tests:

https://github.com/maestro-auth-test/maestro-test2/pull/9519
https://dev.azure.com/dnceng/internal/_git/maestro-test2/pullrequest/6540

Github is nicer in that it actually shows that the app deleted the branch.
In the Azdo PR note that the Delete source branch button is greyed out, and that trying to get to the branch 404s.

### CODE REVIEW

**Comment by riarenas** [comment]
(Unrelated to the PR, but I give up, doesn't matter how many credential configurations I delete, I'm always dotnet-maestro-bot when I commit from this machine)

**Comment by mmitche** [comment]
> (Unrelated to the PR, but I give up, doesn't matter how many credential configurations I delete, I'm always dotnet-maestro-bot when I commit from this machine)

YOu sure that's not the git config?

```
git config -l
...
user.name=Matt Mitchell
user.email=mmitche@microsoft.com
```

**Comment by JohnTortugo** [comment]
> (Unrelated to the PR, but I give up, doesn't matter how many credential configurations I delete, I'm always dotnet-maestro-bot when I commit from this machine)

This happened to me once after I ran the PS scenario tests locally. I was able to fix it later, though. I don't remember exactly how :-/

**Comment by riarenas** [comment]
> YOu sure that's not the git config?
>
>git config -l
>...
>user.name=Matt Mitchell
>user.email=mmitche@microsoft.com

Sadly not. Even in my local git history, the commits are by me, but as soon as I push to GitHub it's maestro-bot. There were some entries in the windows app credentials that had a wrong configuration for a github PAT (possibly by running the scenario tests using the PAT in KV, which belongs to that bot), but I already deleted it, and right before pushing I was even asked for my personal github credentials, which just leaves me more puzzled.

**Comment by riarenas** [comment]
fixed it! did a 
```
git config --global --unset credential.helper
git config --global credential.helper manager
```
and that seems to have deleted any incorrect identity configs.

**Pull request merged**
