### PR TITLE
Pull Core Consumption data from CRP

### PR DESCRIPTION
**Pull request by AlitzelMendez**

### CODE REVIEW

**Comment by garath** [comment]
There's a metric "Total Regional vCPUs" that might be safer if core use ever gets more diverse. The metric "Standard Dv3 Family vCPUs" does cover everything currently so it's probably fine.

**Comment by garath** [comment]
Consider using the Grafana `$__interval` macro for the summarize: `bin(timestamp, $__interval)`. Ideally it makes the nicest graphs.

**Comment by garath** [comment]
The summarize calculates the average core count for a time interval. I think max is a better representation in this case?

**Comment by AlitzelMendez** [comment]
@garath I address all your feedback 



> 
> 
> There's a metric "Total Regional vCPUs" that might be safer if core use ever gets more diverse. The metric "Standard Dv3 Family vCPUs" does cover everything currently so it's probably fine.

you are right this can change 👍 



> 
> 
> Consider using the Grafana `$__interval` macro for the summarize: `bin(timestamp, $__interval)`. Ideally it makes the nicest graphs.

sure! looks a lot better now



> 
> 
> The summarize calculates the average core count for a time interval. I think max is a better representation in this case?

yes, max is better!

**Pull request merged**
