### PR TITLE
Change `SigningInfo` `File` and `Extension` to `Include`

### PR DESCRIPTION
**Pull request by jcagme**
Adapting to change in https://github.com/dotnet/arcade/pull/5899

### CODE REVIEW

**Comment by missymessa** [comment]
Tests? :)

**Comment by jcagme** [comment]
I knew this coming haha. There is no existing test infra for Maestro.Tasks ans while I can add it, it would take a couple of days delaying the signing work. Should we just open a test debt issue for this?

**Comment by missymessa** [comment]
> I knew this was coming haha. There is no existing test infra for Maestro.Tasks ans while I can add it, it would take a couple of days delaying the signing work. Should we just open a test debt issue for this?

Here's the thing: If we open an issue and stick it in our epic, it's very easy to say at the end of the epic, "oh, well, we can just shove off testing into another epic to deal with tech debt later". While we're working on this stuff now, we should be writing tests for it now. If things are broken, we aren't going to discover it here, we're going to discover it in downstream functionality that uses it, which is going to cause problems for that dev who expects the upstream processes to work. And possibly causing delays to fix any bugs that are there. 

My take is that we set a precedence now for incorporating testing as a part of our PRs (as we have been doing on other parts of this epic). Either we take the time now, possibly delaying things, to do the right thing, or we run the risk of delaying things later because we have to push through bug fixes that could've been avoided by having tests. 

Let's not contribute to tech debt now because it's inconvenient for us to write tests.

**Comment by jcagme** [comment]
Agree, also for Maestro.Tasks we don't need a deployment. I'll start working on tests when I have some time

**Comment by jcagme** [comment]
After giving it some extra thoughts and syncing with @markwilkie I'd like to proceed with this PR as is and revisit https://github.com/dotnet/arcade/issues/5903 in a couple of weeks once we have a full signing run. Signing is one of our current business priorities and shouldn't be blocked. Without this change we won't be able to merge artifacts manifests which we need for repos which have more than one manifest. If by then, we can't work on this, I'll move https://github.com/dotnet/arcade/issues/5903 to https://github.com/dotnet/core-eng/issues/10280

**Comment by missymessa** [comment]
I disagree with moving that out of this epic. We should keep it in our epic and strive to get it done as a part of our epic work.

**Comment by jcagme** [comment]
To clarify, intention is to work on it along with the signing work, that the main goal. If there are other priorities by then, which based on the current planning, I don't foresee, then we can analyze whether we'll work on it as part of this epic or whether it makes sense to move it.

**Comment by markwilkie** [comment]
The good news is that we don't need to decide if we move it out of the epic just yet.  The idea is to get through this "crunch", and then evaluate.  

This seems to me to be one of those tricky areas because it's a combination of new surface area, and past debt.  New surface area in the features, but past debt because of the lack of test infra....

I would really love to get this in now - bite the bullet and get it done.  Also, we have to deliver for JoC/Shawn....  Again, we'll know more in a week or two and can re-evaluate.  

I want to say that I do appreciate you pushing on this @missymessa .  I don't even trust myself to always be the right advocate for our tests - and this bites us again and again.

**Comment by markwilkie** [comment]
Is there an issue tracking the test enablement (is this a work??) work?

**Comment by jcagme** [comment]
dotnet/arcade#5903

**Comment by ChadNedzlek** [comment]
When is it _not_ crunch time? This is the reasoning I always see, and it's why our debt it drowning us today.

**Comment by markwilkie** [comment]
What do you propose Chad?

**Comment by ChadNedzlek** [comment]
We need to take testing into account when scheduling work and making sure we plan for that and communicate it when making promises to other teams/upper management.  And then, of course, follow through and do the testing.  Other teams and management are always going to pressure for things faster, and they don't care about the testing, because they just want their feature as fast as possible.  If we don't hold to that, we're going to be ever increasing our debt.

**Comment by markwilkie** [comment]
I agree Chad - and I'm currently assuming (until we learn otherwise) that this testing will get in as part of this epic.  For as you say, it's a priority.  There is a little big of debt to get the testing setup, but it sounds like it's not too too bad.....

**Pull request merged**
