### PR TITLE
Preserve managed feeds outside the comment block

### PR DESCRIPTION
**Pull request by mmitche**
In some rare cases, repository owners want to explicitly place a maestro managed feed into the nuget.config file, and for various reasons, cannot directly reference a dependency that would bring that in in the version.details.xml file. In this specific case, it is because core-sdk needs to redist 3 different versions of the aspnet templates, all of which have the same package name (this is not the case for all templates, some are suffixed with major.minor).

Representing these cases in version.details.xml is a wider issue detailed in #3978. For now, though it's probably best to leave repository owners a workaround by not automatically removing maestro feeds when they are outside the managed feed block.

This change preserves those comments. Tests have been updated.

### CODE REVIEW

**Comment by mmitche** [comment]
@nguerrera @wtgodbe @danmosemsft This is a fix for the issue you saw when attempting to put the 3.0 feed into the 3.1 build.

**Comment by mmitche** [comment]
Fixes https://github.com/dotnet/arcade/issues/4390

**Comment by nguerrera** [comment]
Thanks

**Comment by mmitche** [comment]
fyi it'll probably be a bit of time before this rolls out.

**Pull request merged**
