### PR TITLE
Send along a change note with build information when posting dashboards

### PR DESCRIPTION
**Pull request by garath**
Quality of life improvement: Grafana records a commit message with any dashboard save. This PR teaches the deployment tool to allow sending this message, and modifies the build pipeline to create a message with some deployment tracing info.

### CODE REVIEW

**Review by ChadNedzlek — APPROVED** [review]

**Comment by riarenas** [comment]
@garath it looks like this broke the official build: https://dev.azure.com/dnceng/internal/_build/results?buildId=1559445&view=logs&j=c2e05747-45ee-513b-76dd-1a76a5883b6f&t=3c6b8306-7696-5a6e-47e9-4a7eb2205652

**Comment by garath** [comment]
> it looks like this broke the official build

Investingating

**Comment by ChadNedzlek** [comment]
Probably a space or a quote in something we didn't expect. :-)

**Comment by riarenas** [comment]
Should we revert this until it's figured out?

**Comment by garath** [comment]
> Probably a space or a quote in something we didn't expect. :-)

Good advice. Reverted in dotnet/arcade-services#1804.

**Pull request merged**
