### PR TITLE
[production] Rollout to production

### PR DESCRIPTION
**Pull request by mmitche**

### CODE REVIEW

**Comment by riarenas** [comment]
Build for the rollout: https://dev.azure.com/dnceng/internal/_build/results?buildId=494298&view=results

**Comment by riarenas** [comment]
First attempt at deploying using the new deployment pipeline:

https://dev.azure.com/dnceng/internal/_build/results?buildId=494322&view=results

Failed with 
image

Looking now.

**Comment by riarenas** [comment]
Looks like the variable group in fact does not exist.

There's a `Dotnet Grafana` variable group that is also used from another yaml file that might be the right one, or we might actually need a new one? 

@ChadNedzlek Is it supposed to be the same variable group and a rename is needed? or is `Dotnet Grafana` supposed to be separate? I see that both variable groups have different secrets linked.

**Comment by ChadNedzlek** [comment]
The keys will be different, so we need another one. I'll make it real quick.

**Comment by ChadNedzlek** [comment]
I've created the variable group.

**Comment by riarenas** [comment]
Thanks! queued https://dev.azure.com/dnceng/internal/_build/results?buildId=494517&view=results

**Comment by sunandabalu** [comment]
> Thanks! queued https://dev.azure.com/dnceng/internal/_build/results?buildId=494517&view=results

Damn, I queued one too - https://dev.azure.com/dnceng/internal/_build/results?buildId=494518&view=results

**Comment by riarenas** [comment]
Cancelled one of them.

**Comment by riarenas** [comment]
https://dev.azure.com/dnceng/internal/_build/results?buildId=494517&view=results is the one that is still running.

**Comment by riarenas** [comment]
Couple of post-deployment issues so far: 

* https://github.com/dotnet/core-eng/issues/8638
* https://github.com/dotnet/core-eng/issues/8639

**Comment by riarenas** [comment]
Deployment just finished running the Maestro scenario tests. The two issues above seem to be the only ones that popped up this time.

**Comment by riarenas** [comment]
Sigh, @mmitche reported another problem with the deployment. It looks like when queueing the deployment pipeline, even when queued for the production branch, the deployment pipeline picks up the artifacts from the latest successful build, regardless of branch. We ended up deploying artifacts from a master build instead of production.

**Comment by ChadNedzlek** [comment]
That's... really bad... We should probably restart the whole thing.

**Comment by riarenas** [comment]
Starting a new production build from scratch will hopefully trigger a deployment for the right artifacts. Starting over.

**Comment by riarenas** [comment]
New build: https://dev.azure.com/dnceng/internal/_build/results?buildId=495165&view=results

**Comment by riarenas** [comment]
Build triggered this deployment which is using the right artifacts: https://dev.azure.com/dnceng/internal/_build/results?buildId=495249&view=results

**Pull request merged**
