### PR TITLE
[Rollout] Production rollout 5/27/2020

### PR DESCRIPTION
**Pull request by riarenas**
Looks like the 3.1 saga is finally over?

Master build: https://dev.azure.com/dnceng/internal/_build/results?buildId=657752&view=results

### CODE REVIEW

**Comment by riarenas** [comment]
@ChadNedzlek let me know if there's anything you still want to take a look at

**Comment by ChadNedzlek** [comment]
I... think everything is working ok?  The arcade update is perma-blocked, which sucks (because the test reporting is all screwed up), and the scenario tests seem to be failing intermittently... And one the last fixes I only got at the very last minute...

But I think things are fine?

**Comment by riarenas** [comment]
Yeah I think things are OK. I'll bring up the fact that it's potentially noisy and that the last fixes went in recently during standup. We can decide if it's too risky.

**Comment by ChadNedzlek** [comment]
Ooops, I screwed up https://github.com/dotnet/arcade-services/commit/feda62d00c7c6c67df2d35129ba7e97ee598aef9 That commit is clearly missing an S. :-(

**Comment by riarenas** [comment]
Closing this to give the latest fixes a little bake time. If there's anything you really want rolled out let me know to see if it's worth making adjustments.

**Pull request closed without merging**
