### PR TITLE
Use --config-env to pass in User and PAT during Git Checkout

### PR DESCRIPTION
**Pull request by kythant**
This is to stop Geneva from logging the user and PAT in the command line

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/arcade-services?pullRequest=2081) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/arcade-services?pullRequest=2081) before we can accept your contribution.<br/><br/>:x: kythant [sign now](https://cla.dotnetfoundation.org/dotnet/arcade-services?pullRequest=2081)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/arcade-services?pullRequest=2081) it.</sub>

**Review by alexperovich — COMMENTED** [review]
This looks fine. I'd like some more people to look at it though.

**Review by MattGal — APPROVED** [review]

**Comment by kythant** [comment]
@MattGal @alexperovich Can someone help me with the process of validating this fix in the integration environment?

**Comment by alexperovich** [comment]
Just merging it will push it to our staging environment and run the scenario tests that will validate it.

**Pull request merged**
