### PR TITLE
[production] Production rollout 3/11/2020

### PR DESCRIPTION
**Pull request by mmitche**

### CODE REVIEW

**Comment by alexperovich** [comment]
This PR should probably not be directly from master -> production. My PR I just merged should probably not be deployed tomorrow. This needs to be from a branch at this commit https://github.com/dotnet/arcade-services/pull/1024/commits/47a35ee16b3a9e44fb0058fc8b70f85ccb589185.

**Comment by riarenas** [comment]
We've been doing these directly from master to production for a while, and we hold off on merging changes when we know a rollout is about to happen. I'll make sure we have more explicit guidance on how to create a branch for the rollout and do it from there so that we can avoid these problems.

I'll recreate the PR from a manually created branch after lunch.

**Comment by alexperovich** [comment]
Ahh, I was unaware that this would be affected by my merge. I wanted to get the master build started so I can validate it.

**Comment by riarenas** [comment]
There's technically no reason to do it this way, it's just faster 😁

**Pull request closed without merging**
