### PR TITLE
Disable nullable annotations and standardize on C# 11

### PR DESCRIPTION
**Pull request by ChadNedzlek**
It's difficult to work in a project when the rules of C# change from project to project (or for nullable, from file to file).

At least normalize on something that's usable and we can deal with changes without having lindmines of language features.

### CODE REVIEW

**Review by alexperovich — APPROVED** [review]

**Comment by ChadNedzlek** [comment]
Looks like I have to just remove them all. We can't start in the middle with nullable. It's a bottom up thing. And "Microsoft.Dotnet.Services.Utility" and "Internal.Logging" are below "DarcLib", so they need annotations before they can safely be enabled in there.

**Comment by ChadNedzlek** [comment]
If a library in the middle starts with nullable, it places weird constraints on assemblies it depends on, where things need to be both nullable and not. They can't be _marked_ nullable, because that assembly doesn't allow nullable. But they can't be marked no nullable either, or the assembly that has nullability enabled throws errors.  And it can mean that all of the sudden, features or bugs can't be fixed without a mountain of work because of that fork.

**Comment by garath** [comment]
Deleting existing annotations seems like a step backwards. Is there really no way to let those live and get the pieces of code that don't understand annotations to do the right thing?

I may be confused. Two things catch me: 

- The libraries have been iteratively adding annotations since the feature was released. Those are low-level but didn't prevent apps from adopting nullable (though certainly upgrades are more dramatic when the annotations show up).
- I can create an app that does not use nullable but also does not catch drama from nullable-enabled dependencies.

**Comment by ChadNedzlek** [comment]
@garath, no there isn't. That's why it's so important that we start from the bottom.  I tried turning it to "annotation" only mode, but that still caused the build to fail with warnings as errors.  It shouldn't be _too_ hard to annotate the libraries that darc depend on, but we _can't_ just be haphazard about this, since it leads to huge maintenance headaches later.

**Comment by ChadNedzlek** [comment]
The libraries, importantly, _started at the bottom_.  They didn't add nullable to a library until all the libraries it depended on had already done it. That's the same approach we need to take. They didn't just randomly do it, they had a plan that followed the dependency tree.

**Review by alexperovich — APPROVED** [review]

**Comment by premun** [comment]
Please, don't merge this PR. You are removing a lot of effort I have put into new code that was added in the last 2 months.

Like @garath says, it is a step backwards to remove existing annotations even when they are being used per-file. There is no drawback from using this in new files and it is very much possible to adopt the feature piece by piece as you change files. The feature was [designed exactly this way actually](https://devblogs.microsoft.com/dotnet/embracing-nullable-reference-types/).

I have personally gone through this process when adopting [~30 000 lines of code from Xamarin](https://github.com/dotnet/xharness/tree/main/src/Microsoft.DotNet.XHarness.iOS.Shared) and turned nullability for most of the code slowly over the course of 2 years while the other projects where started with nullability enabled side-by-side. It was a very safe process which improved the code greatly and uncovered many potential NREs. The XHarness tooling hasn't had NREs since I remember.

I really don't understand your point of having nullable and non-nullable code side by side. If you call into non-nullable library.. well, bad luck, you need to code defensively as you can get a null. BUT you need to do that regardless of whether the calling code is nullable or not. So.. I don't really see the problem nor I have encountered any issue. For this reason, I agree it's better to go bottom-up and start in the lowest layer, but it doesn't mean you cannot add new code in the middle that already takes nullability into account. For instance, in this PR, you have removed nullability from a whole new namespace I have added and that also doesn't make sense. You only need to code defensively at the edge of the nullable code and once you're in, you can take advantage of the feature in full.

**Review by premun — CHANGES_REQUESTED** [review]
Please do not merge this and make all the effort I put into the new code go in vain.

**Comment by premun** [comment]
I would still vote to keep the portion of this change that standardizes on C# 11

**Pull request closed without merging**
