### PR TITLE
Fix maestro endpoint

### PR DESCRIPTION
**Pull request by ChadNedzlek**
My arcade build seems to be ok, but there is some failing test that's preventing me from getting to the last point, but it looks like it should work...

### CODE REVIEW

**Comment by markwilkie** [comment]
What do you mean @ChadNedzlek by failing tests?

**Comment by riarenas** [comment]
I dislike that I can't add comments for lines that a PR is not changing...
Could you add
```
batch: true
```
To LN 14 of the azure-pipelines.yml? Two PRs that get merged in a short timespan are causing failures to deploy the services:

https://dev.azure.com/dnceng/internal/_build/results?buildId=433016&view=results
https://dev.azure.com/dnceng/internal/_build/results?buildId=433042&view=results

**Comment by riarenas** [comment]
@markwilkie We discovered a few scenario test failures from recent changes / the way that the azdo tasks run the tests, and we're only getting to fix them now that the build pipeline has been mostly unblocked.

https://github.com/dotnet/arcade-services/pull/793 and https://github.com/dotnet/arcade-services/pull/788 have various test fixes for these situations.

**Comment by ChadNedzlek** [comment]
@mmitche Yes, and that one is important. The scenario tests use it. I removed it from the build because nothing in the build used this variable, and it was confusing.

@riarenas I'll add the batch line.

**Comment by ChadNedzlek** [comment]
@riarenas I think I enabled batching...   Part of the problem might also have been that I've been deploying from another branch (which is what our policy says to do), so it's likely my deployments have been causing conflicts with the master deployments, because they are all deploying to the same resources simultaneously)

**Comment by riarenas** [comment]
@ChadNedzlek The batching looks good. The two builds i linked were from master this morning, and they both got to the deployment phase at around the same time and both ended up failing. The batching will help with this. I think having a separate branch also deploying to INT will result in the same problem, but that usually happens less often.

**Pull request merged**
