### PR TITLE
Deploy master to PROD

### PR DESCRIPTION
**Pull request by JohnTortugo**
Any problem deploying this to PROD?

### CODE REVIEW

**Comment by alexperovich** [comment]
I'd like to get https://github.com/dotnet/arcade-services/pull/364 in before we deploy this if possible.

**Comment by mmitche** [comment]
@JohnTortugo What's the purpose of this rollout? We're in P5 shutdown so i'm very risk adverse.

**Comment by mmitche** [comment]
@JohnTortugo I'd like to remove the default channel enable/disable from this.

**Comment by jcagme** [comment]
@JohnTortugo I guess that if you really need this, and the need is justifiable based on preview 5 coming in hot, you could just cherry pick your change and put it in prod, but I agree with Matt that we should be careful on what we deploy.

**Comment by JohnTortugo** [comment]
Wanted to get more logging to debug this issue: https://github.com/dotnet/arcade/issues/2334

I'm OK with postponing this.

**Pull request closed without merging**
