### PR TITLE
Fix invalid Includes in older version of the ChannelsController

### PR DESCRIPTION
**Pull request by riarenas**
Fixes https://github.com/dotnet/core-eng/issues/10124

### CODE REVIEW

**Comment by ChadNedzlek** [comment]
Could we add some tests in the vein of the BuildCoontrollerTests? :-)

**Comment by riarenas** [comment]
I can definitely write some tests, but I think they should come as a separate PR if we still want to roll out this week.

**Comment by riarenas** [comment]
Actually, we have the tests that would catch this but only for the 20200220 API.

**Comment by riarenas** [comment]
Added tests for this controller version.

**Pull request merged**
