### PR TITLE
removed old build monitor configs

### PR DESCRIPTION
**Pull request by missymessa**
https://github.com/dotnet/arcade/issues/13310

@dkurepa I'll migrate these changes to dotnet/dnceng after your PR into that repo gets sorted.

### CODE REVIEW

**Comment by garath** [comment]
> In the meantime, Alex doesn't need to be getting these notifications anymore, and since the direction from LT that we are no longer maintaining it, we don't need the Build Monitor issues for that service.

I understand the idea but want to express my preference that we keep all the monitoring up and only take it down once something has happened that we've decided we're not going to act on.

**Comment by missymessa** [comment]
Who is going to pay attention to the pipeline failures then? Because we can't assign those issues to Alex anymore.

**Comment by garath** [comment]
> Who is going to pay attention to the pipeline failures then? Because we can't assign those issues to Alex anymore.

To SSA / Operations. It should be treated like any of our other services (and should have been even back when Alex was handling it 😁 )

**Comment by markwilkie** [comment]
Yep - it's official we are no longer supporting source.net.  cc/ @shawnro

**Comment by missymessa** [comment]
This code moved to dnceng. Changes handled along side other changes for changes to issue management. https://github.com/dotnet/dnceng/pull/18

**Pull request closed without merging**
