### PR TITLE
Remove PublishingUsingPipelines from code base

### PR DESCRIPTION
**Pull request by JohnTortugo**
Relates to: https://github.com/dotnet/arcade/issues/4707

Basically assume that PublishingUsingPipelines is true wherever it's used. I'll update Maestro.Client in a subsequent PR.

### CODE REVIEW

**Comment by mmitche** [comment]
So with this change, the original REST API output fields stay the same right?

**Comment by JohnTortugo** [comment]
Talked offline. I'll make some changes before merging the PR.

**Comment by JohnTortugo** [comment]
@mmitche - PTAL when you can.

**Pull request merged**
