### PR TITLE
Add WEBSITE_RUN_FROM_PACKAGE setting to Status site deployment

### PR DESCRIPTION
**Pull request by meganaquinn**
Testing to see if the deploy.yaml is the correct spot to add this - there are several options and it's not entirely clear which one we use. Unless someone knows for sure I'm just going to try deploying this and see if it works (there another project that uses this approach for the settings that end up in the Configuration tab on Azure).

### CODE REVIEW

**Review by ChadNedzlek — CHANGES_REQUESTED** [review]
The documentation says that if you aren't using "zipDeploy" this setting won't work. I think this will just break stuff... https://docs.microsoft.com/en-us/azure/azure-functions/run-functions-from-deployment-package#enabling-functions-to-run-from-a-package

**Comment by meganaquinn** [comment]
> The documentation says that if you aren't using "zipDeploy" this setting won't work. I think this will just break stuff... https://docs.microsoft.com/en-us/azure/azure-functions/run-functions-from-deployment-package#enabling-functions-to-run-from-a-package

Well I'm officially confused. Adding this setting (set to 0) in the portal is what let me successfully deploy the status site yesterday. I confirmed it by removing the setting and the deployment failure came back (then adding it back again so that newer deployments would succeed). This doc doesn't even mention that value as an option.

I found this, which seems to indicate that we shouldn't be seeing this problem since we're explicitly setting webDeploy as the deployment type: https://www.brandonbarnett.io/blog/2019/02/why-isnt-azure-app-service-deploy-copying-files-to-my-web-apps-wwwroot/

And in addition a deploy just succeeded without that setting existing. So I guess I'm pulling this PR while I try to figure out what happened.

**Comment by ChadNedzlek** [comment]
Does it actually DO anything though?  Setting that value essentially means "don't run what I'm deploying", if you aren't doing a zip thing, so it makes sense that the deployment would work, since nothing would be even looking at it... It sounds like there is some weird file in use problem here.  Something during the deployment causes that file to get locked, and then it can't overwrite it. :-(

**Comment by ChadNedzlek** [comment]
Try changing something on the main page or something and see if the new version is loading.  Maybe the documentation isn't right? Though at that point I'm not sure what "package" it's executing from... since we haven't uploaded any packages.

**Comment by ChadNedzlek** [comment]
Oh! Wait, this is setting it to zero... but isn't it already set to zero?  Or maybe someone set it to true on the service, and that's the whole problem?

**Review by ChadNedzlek — APPROVED** [review]
I didnt see it was zero... I retroactively approve?

**Review by MattGal — APPROVED** [review]

**Comment by meganaquinn** [comment]
> Oh! Wait, this is setting it to zero... but isn't it already set to zero? Or maybe someone set it to true on the service, and that's the whole problem?

The theory is that that's the problem - we aren't setting it anywhere but true has been the default for new App Services for a couple years so my best guess is that someone on the backend did something that assumes that default in services that don't have the value set. It doesn't explain why it still works after the value is overwritten in the config (maybe they fixed the bug?), but this is more of a safety net in case it happens again.

I'd prefer to know why/how this whole thing happened, but there isn't a great way to do that. :( So I'm settling for a safety net that ideally just doesn't do anything most of the time.

**Comment by riarenas** [comment]
@meganaquinn this change is breaking the deployment again:

https://dev.azure.com/dnceng/internal/_build/results?buildId=926596&view=results

```
Trying to update App Service Application settings. Data: {"":"0"}
##[error]Error: Failed to update App service 'dotneteng-status-staging-staging' application settings. Error: BadRequest - Parameter name cannot be empty. (CODE: 400)
```

I'm going to revert it to see if we can get a clean build of arcade-services today.

**Comment by riarenas** [comment]
Revert PR: https://github.com/dotnet/arcade-services/pull/1500

**Pull request merged**
