### PR TITLE
Fixes to darc-add-build-to-channel

### PR DESCRIPTION
**Pull request by riarenas**
* Enable darc-add-build-to-channel to promote builds from Devdiv: 
This is for https://github.com/dotnet/arcade/issues/4986 and is needed to get NuGet insertions into .NET working again.

  Triggered https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3556040&view=logs&j=f7bb3748-e35d-53de-9dd7-460ecd2014d6&t=299a6d6d-a279-539e-b6e9-1576018947a8 with these changes.

* Also fixes some validation errors that weren't failing the operation due to a bug in the validation code: dotnet/arcade#4941

### CODE REVIEW

**Comment by JohnTortugo** [comment]
@riarenas - Perhaps you could add the fix to the build validation method in this PR? The if error cases need to return false instead of true.

**Comment by riarenas** [comment]
>@riarenas - Perhaps you could add the fix to the build validation method in this PR? The if error cases need to return false instead of true.

I sent this now to cover our bases for this week's deployment in case I'm not able to validate all the error scenarios that I want. If I finish the other changes I'll include them here, otherwise I'll send a second PR tomorrow.

**Comment by riarenas** [comment]
Specifically, the errors we're getting from unauthorized azdo pats are not what I was expecting so still debugging that.

**Comment by riarenas** [comment]
Ah NVM, I was cancelling the command too early, the error message is just behind the retries we still have for 401s. It is indeed just as simple as returning false instead of true when validating the different parts of the build. change incoming.

**Comment by riarenas** [comment]
This is now also the PR for https://github.com/dotnet/arcade/issues/4941

**Pull request merged**
