### PR TITLE
Use file-scoped namespaces

### PR DESCRIPTION
**Pull request by alexperovich**
This was a purely mechanical change. Other than fixing TestDataReceiver to handle the file scoped namespace declarations.

### CODE REVIEW

**Comment by garath** [comment]
Another battle won in the war against curly braces 😄

**Comment by ChadNedzlek** [comment]
I'd like to let people have a chance to look at this before we merge it, since it's basically changing one of our implicit "style rules", and might cause exciting merge conflicts, but I'm happy to go with the will of the people on this one... I'm basically equally for and against the feature.

**Comment by alexperovich** [comment]
Yup, I'm gona leave it as a draft for a few days so people can weigh in.

**Review by premun — APPROVED** [review]
In my opinion, this feature is just goodness and improves UX when reviewing code as you get 8 columns of horizontal estate back. I am strongly for this. I also think it's the recommended style based on our `.editorconfig` here (I think it's default now and I see VS hints all the time).|

I would, however, not wait with this for a long time as @ChadNedzlek suggest as other people working in other branches will have nasty conflicts. OR leave it here for some time but then take a fresh main before merging and run the refactoring again as it's less work that way.

**Review by missymessa — APPROVED** [review]
I'm fine with this. No preference either way. 

image

image

**Review by MattGal — APPROVED** [review]

**Review by MattGal — APPROVED** [review]

**Pull request merged**
