### PR TITLE
Upgrade dotnet and ignore end of life error

### PR DESCRIPTION
**Pull request by adiaaida**
In order to ignore the end of life error we were seeing, we need to add /p:CheckEolTargetFramework=false to symbol publishing and artifacts publishing.

Official pipeline for testing: https://dev.azure.com/dnceng/internal/_build/results?buildId=1680554&view=results

### CODE REVIEW

**Review by mmitche — APPROVED** [review]

**Comment by ChadNedzlek** [comment]
Where is the reference to 2.1 coming from. Do we have an actual dependency on some EOL'd thing?

**Comment by adiaaida** [comment]
@ChadNedzlek arcade-services uses the release/5.0 version of arcade which is where the netcoreapp2.1s are coming from. Since we are only using it to publish the symbols/artifacts, this is a stopgap that should be ok. The real fix would be to actually fix arcade to not use 2.1.

**Comment by ChadNedzlek** [comment]
I don't suppose there is a bug somewhere to get arcade off of 2.1 in general? That seems like that would be good, so that people don't have to start plastering this warning in more and more places.

**Comment by adiaaida** [comment]
Well, mmitche's gonna have to do it if he wants https://github.com/dotnet/arcade/pull/8626 to go in

**Comment by mmitche** [comment]
> Well, mmitche's gonna have to do it if he wants [dotnet/arcade#8626](https://github.com/dotnet/arcade/pull/8626) to go in

Ouch! Can't move to 5.0 either, since that goes EOL in 2 months.

**Comment by adiaaida** [comment]
3.1 is also EOL isn't it?

**Comment by ChadNedzlek** [comment]
3.1 gets us at least into December.  But this means we are in for a giant upgrade soon for all our service code to go from 3.1 to 6. Hopefully it's not as painful as 2.1 to 3.1... but I'm not optimistic... it took me almost 6 months last time.

**Pull request merged**
