### PR TITLE
Improve commit message

### PR DESCRIPTION
**Pull request by epananth**
[Edit - changed issue number]

Issue => https://github.com/dotnet/arcade/issues/5453

Removing commit message redundancy.

### CODE REVIEW

**Comment by riarenas** [comment]
Could you provide an example of how a PR looks after your change?

**Comment by epananth** [comment]
Currently the commit message : 

* Update dependencies from https://github.com/dotnet/aspnetcore-tooling build 20200507.9

- Microsoft.AspNetCore.Mvc.Razor.Extensions: 5.0.0-preview.5.20257.7 -> 5.0.0-preview.5.20257.9
- Microsoft.AspNetCore.Razor.Language: 5.0.0-preview.5.20257.7 -> 5.0.0-preview.5.20257.9
- Microsoft.CodeAnalysis.Razor: 5.0.0-preview.5.20257.7 -> 5.0.0-preview.5.20257.9
- Microsoft.NET.Sdk.Razor: 5.0.0-preview.5.20257.7 -> 5.0.0-preview.5.20257.9


After this change

* Update dependencies from https://github.com/dotnet/aspnetcore-tooling build 20200507.9

-Microsoft.AspNetCore.Mvc.Razor.Extensions , Microsoft.AspNetCore.Razor.Language , Microsoft.CodeAnalysis.Razor , Microsoft.NET.Sdk.Razor
From Version 5.0.0-preview.5.20257.7 -> To Version 5.0.0-preview.5.20257.9

**Comment by epananth** [comment]
Discussed with @riarenas there is another corner case 

https://github.com/dotnet/arcade-validation/commit/e788b97ac520e319ab16d7914f10beaae8defd77

If the dependency update is from the same repo and the builds differ then just get the latest build number and discard the older ones.

**Comment by mmitche** [comment]
> I don't think this is what we want.
> 
> The original issue is that if there are multiple dependency updates in the same PR, or external commits to the dependency updates, the final commit message ends up being unreadable due to the length:
> 
> [dotnet/aspnetcore@771989b](https://github.com/dotnet/aspnetcore/commit/771989b71dbfcdfed4093a5087948fbe87445bd6)
> 
> Even if you condense some version string, we are still appending to the description over and over, so in the end we will still end up with the giant commit message.

I think we still want this bit of change too.  The number of dependencies updated in some repos is very large, and likely to get larger, so condensing is one step towards making it workable. I think we should keep this change, even if we do additional ones.

**Pull request merged**
