### PR TITLE
[Rollout] Production Rollout 4/22/2020

### PR DESCRIPTION
**Pull request by sunandabalu**

### CODE REVIEW

**Comment by riarenas** [comment]
I think we want https://github.com/dotnet/arcade-services/pull/1117 in this as well to fix dotnet-status.

**Comment by ChadNedzlek** [comment]
@riarenas Agreed and merged. My AzDO builds were being difficult.

**Comment by sunandabalu** [comment]
I will wait for the master build to finish successfully to include the change.

**Comment by sunandabalu** [comment]
Included @ChadNedzlek 's change as well.

**Pull request merged**
