### PR TITLE
Upgrade the dotnet version to 5.0.406, so that we are on the latest version (5.0.15)

### PR DESCRIPTION
**Pull request by adiaaida**
Addresses the maestro-int and maestro-prod aspects of https://github.com/dotnet/core-eng/issues/15720

### CODE REVIEW

**Review by riarenas — APPROVED** [review]
It's not super clear to me how https://github.com/dotnet/core-eng/issues/15720 is involved here but lgtm

**Review by mmitche — APPROVED** [review]

**Comment by ChadNedzlek** [comment]
This appears to have, somehow, broken the build.  We might need to revert this.

**Comment by ChadNedzlek** [comment]
Or fix whatever is causing Symbol Publish to fail

**Comment by ChadNedzlek** [comment]
Either this one or https://github.com/dotnet/arcade-services/pull/1857.

Neither really makes any sense to have broken it, but one of them looks like it did.

**Comment by MattGal** [comment]
https://dnceng.visualstudio.com/internal/_build/results?buildId=1680237&view=results should show us whether stuff's behaving.  Given I moved from an MMS image to an MMS image, the build images should not matter, but who knows....

**Pull request merged**
