### PR TITLE
Remove AutoBuildPromotion infra

### PR DESCRIPTION
**Pull request by JohnTortugo**
Relates to: https://github.com/dotnet/arcade/issues/4725

We don't need this check anymore. It's been a few weeks that `autoBuildPromotion == false`.

### CODE REVIEW

**Comment by riarenas** [comment]
LGTM. When you merge, please give the commit a more descriptive name :)

**Comment by missymessa** [comment]
This is a great name for a PR.

**Comment by JohnTortugo** [comment]
Oh boy. The things you do when your wife is looking weird at you.

**Comment by missymessa** [comment]
> Oh boy. The things you do when your wife is looking weird at you.

... so, what happened? You can't end the story there!

**Comment by JohnTortugo** [comment]
> > Oh boy. The things you do when your wife is looking weird at you.
> 
> ... so, what happened? You can't end the story there!

I had lunch on time today. :-)

**Pull request merged**
