### PR TITLE
Onboard dn-bot for https://domoreexp.visualstudio.com/

### PR DESCRIPTION
**Pull request by RussKie**
https://github.com/dotnet/arcade/issues/11798 is the issue tracking supporting the domoreexp org.

### CODE REVIEW

**Comment by RussKie** [comment]
@MattGal  @mmitche would this be all that's required?

**Comment by mmitche** [comment]
I think it looks about right? Right now we're trying to figure out how to fund this, so please stand by.

**Review by MattGal — APPROVED** [review]

**Comment by MattGal** [comment]
@RussKie dn-bot has not been added to domoreexp.visualstudio.com, let's chat about that when you're available.

**Comment by RussKie** [comment]
@tekian is helping on the R9 side, he said it's added...

**Pull request merged**
