### PR TITLE
Revert hardcoding darc version

### PR DESCRIPTION
**Pull request by missymessa**
Last change needed for https://github.com/dotnet/arcade/issues/9948

Need to hold off on merging this PR until after the artifact change in OSOB rolls out.

### CODE REVIEW

**Review by adiaaida — APPROVED** [review]

**Review by riarenas — APPROVED** [review]

**Comment by riarenas** [comment]
> Need to hold off on merging this PR until after the artifact change in OSOB rolls out.

I will go one step further and ask that this isn't merged until we've validated in the prod build pools that we can install newer versions of darc without yaml changes

**Comment by riarenas** [comment]
I will just block this until then just in case I think, feeling a bit paranoid this morning.

**Review by riarenas — CHANGES_REQUESTED** [review]
Just blocking until we've validated the scenario in the prod pools, just in case this slips through the cracks and gets merged by mistake.

**Comment by riarenas** [comment]
Running a test build here: https://dev.azure.com/dnceng/internal/_build/results?buildId=1965007&view=results If that succeeds we're good to merge!

**Comment by riarenas** [comment]
The initial test worked, but I realized my branch was out of date with main enough that we even changed which pools we use for the publishing templates. I don't expect any difference in results, but just in case https://dev.azure.com/dnceng/internal/_build/results?buildId=1965141&view=results is the new build to watch

**Review by riarenas — APPROVED** [review]
Everything looks good now Yay

**Pull request merged**
