### PR TITLE
[Rollout] Merge master into Production

### PR DESCRIPTION
**Pull request by riarenas**
Preparing the PR for tomorrow's rollout.

### CODE REVIEW

**Comment by ChadNedzlek** [comment]
Looks good to me... I don't think I've even done anything that will break the prod rollout this time either. :-)

**Comment by mmitche** [comment]
@riarenas @JohnTortugo do we have the right feature flags in place for this rollout?

**Comment by JohnTortugo** [comment]
@mmitche - Yeah, we have `AutoBuildPromotion` in a maestroprod App Configuration (container) set to True.

**Comment by mmitche** [comment]
> @mmitche - Yeah, we have `AutoBuildPromotion` in a maestroprod App Configuration (container) set to True.

Okay...that's the current behavior or the new behavior? And if it's the new behavior we have all the other pieces in place so that the transition is seamless?

**Comment by JohnTortugo** [comment]
> > @mmitche - Yeah, we have `AutoBuildPromotion` in a maestroprod App Configuration (container) set to True.
> 
> Okay...that's the current behavior or the new behavior? And if it's the new behavior we have all the other pieces in place so that the transition is seamless?

It's the old behavior.

**Comment by riarenas** [comment]
Going to merge this now to open master for changes.

**Comment by riarenas** [comment]
https://dev.azure.com/dnceng/internal/_build/results?buildId=517824&view=results is queued and waiting for approval. I'll approve it closer to noon, which is when we informed partners that we'd be doing the deployment.

**Pull request merged**
