### PR TITLE
Remove release pipeline runner service

### PR DESCRIPTION
**Pull request by JohnTortugo**
Once we merge [this other PR](https://github.com/dotnet/arcade-services/pull/1020) we won't be triggering any release pipeline therefore we can remove the release pipeline runner.

### CODE REVIEW

**Comment by JohnTortugo** [comment]
Now that our roll out PR is not from master I'll merge this PR today.

**Comment by riarenas** [comment]
@johntortugo this seems to have broken the master build: https://dnceng.visualstudio.com/internal/_build/results?buildId=556326&view=results

**Comment by ChadNedzlek** [comment]
I'm considering reverting this change. It breaks our int builds, and it will break our next production rollout.

We can always just make the service do nothing until we solve the "how to delete a service" problem.

**Comment by riarenas** [comment]
@JohnTortugo  is looking at this in https://github.com/dotnet/core-eng/issues/9353

**Pull request merged**
