### PR TITLE
Use comment markers to update PR descriptions for a given subscriptio…

### PR DESCRIPTION
**Pull request by riarenas**
…n in place instead of appending on every update

https://github.com/dotnet/arcade/issues/2219

This change makes it so we don't keep appending updates to dependency flow PRs in the description, but instead add invisible markers so that we can change the description in-place. Adds the following markers:

* One marker for each different subscription
* One marker for coherency updates

Validated this in the following PRs:

* non-batched: https://github.com/riarenas/maestro-test1/pull/7
* AzDO batched: https://dev.azure.com/dnceng/internal/_git/maestro-test2/pullrequest/1544?_a=overview
* Github Batched: https://github.com/riarenas/maestro-test1/pull/6
* With Coherency updates: https://github.com/maestro-auth-test/maestro-test3/pull/119

On each of these you will see multiple commits, but there's a single section per subscription.

### CODE REVIEW

**Comment by mmitche** [comment]
AWESOME

**Comment by riarenas** [comment]
All credit goes to @alexperovich for the idea of using the invisible markers. My previous code for this was getting out of hand to keep a record of all the previous updates so that we didn't stomp on batched subscriptions when a new update came in.

**Comment by riarenas** [comment]
Incidentally, this fixes dotnet/arcade#2244 which I just learned existed.

**Comment by mmitche** [comment]
> Incidentally, this fixes [dotnet/arcade#2244](https://github.com/dotnet/arcade/issues/2244) which I just learned existed.

BONUS bug!

**Pull request merged**
