### PR TITLE
Add Do Not Automerge Downgrades policy to UX

### PR DESCRIPTION
**Pull request by mmitche**
This got missed when the policy was added at some time back. It's part of the standard policy but not settable independently. Add to the UX

### CODE REVIEW

**Comment by mmitche** [comment]
@dougbu I set the 7.0/7.0-rc1 policies with this.

**Review by riarenas — APPROVED** [review]
LGTM. Didn't even get to look at this after lunch. Now that's service!

**Review by dougbu — APPROVED** [review]
Many thanks❕❕

**Comment by dougbu** [comment]
> @dougbu I set the 7.0/7.0-rc1 policies with this.

Awesome. And it already shows up in the `darc get-repository-policies` output 😄 

How long after merging this will a new `darc` be available❔ I'll handle release/6.0 and main a bit after that.

**Comment by riarenas** [comment]
@dougbu 

As this change doesn't require service changes and it's strictly in darc, you can install the version generated by the official build once this change is merged. I can give you the version you can pass as a parameter to the darc init scripts.

It will take at least one more deployment to production for this to be in the standard version that you get when calling the init script without overrides, so at the very earliest, next Wednesday.

**Comment by dougbu** [comment]
> I can give you the version you can pass as a parameter to the darc init scripts.

Thanks. That sounds like a great option because I'd not give myself time to forget about this 😉 Much appreciated.

**Comment by riarenas** [comment]
@dougbu 

`darc-init.ps1 -darcVersion 1.1.0-beta.22425.1` should get you sorted

**Pull request merged**
