### PR TITLE
Fix failure with users in more than 30 orgs

### PR DESCRIPTION
**Pull request by alexperovich**

### CODE REVIEW

**Comment by riarenas** [comment]
What went wrong the last time?

**Comment by alexperovich** [comment]
I removed a bit too much from the GitHubAuthenticationOptions.

**Comment by ChadNedzlek** [comment]
Why didn't the DependencyRegistration tests catch that?

**Comment by alexperovich** [comment]
It wasn't something not registered, I just removed setting a required property.

**Comment by ChadNedzlek** [comment]
oooo, yeah, we'd never catch that in a test. :-)

**Comment by riarenas** [comment]
This broke again. Made it so Github would return an error page when trying to authenticate the maestro token. See https://github.com/dotnet/core-eng/issues/10023

**Comment by alexperovich** [comment]
Does it happen with a bad token? or any token?

**Comment by riarenas** [comment]
Any token

**Pull request merged**
