### PR TITLE
Onboard new inter-branch merge flow [Workflow]

### PR DESCRIPTION
**Pull request by f-alizada**
### Context
Onboarding new merge flow based on the github actions

### Changes Made
Added github workflow for the branch.

### References
Documentation https://github.com/dotnet/arcade/blob/main/Documentation/Maestro/New-Inter-Branch-Merge-Approach.md
One pager: https://github.com/dotnet/dnceng/blob/main/Documentation/OnePagers/github-action-inter-branch-merge.md

### CODE REVIEW

**Review by premun — APPROVED** [review]

**Comment by premun** [comment]
@f-alizada is it on purpose that this is targeting `production` and not `main`?

**Comment by f-alizada** [comment]
> @f-alizada is it on purpose that this is targeting `production` and not `main`?

Yes it is. 
In order for the github workflow to work on the branch (in this case `production` ) the workflow has to be presented in the PR targeting branch. 
Could you please let me know if this is a blocker for moving to the new flow of merging?

**Comment by premun** [comment]
Ah, no, all good then

**Comment by oleksandr-didyk** [comment]
Not sure if this is related, but there seems to be some permissions missing. This is an exception I got after my rollout branch merge in `production` - https://github.com/dotnet/arcade-services/actions/runs/9658989332/job/26641354075#step:7:49

image

**Comment by f-alizada** [comment]
> Not sure if this is related, but there seems to be some permissions missing. This is an exception I got after my rollout branch merge in `production` - https://github.com/dotnet/arcade-services/actions/runs/9658989332/job/26641354075#step:7:49

Thank you for pointing out! 
Yes indeed the permission to create the PR's is missing. 

There is an item related to this mentioned in the doc: https://github.com/dotnet/arcade/blob/main/Documentation/Maestro/New-Inter-Branch-Merge-Approach.md

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#preventing-github-actions-from-creating-or-approving-pull-requests

In order for GitHub action to create the PullRequest it should be explicitly updated in the setting, once updated the workflow could be re-run and it should create similar to this PR https://github.com/dotnet/arcade-services/pull/3676.

Please feel free to reach out in case additional input is needed.

**Comment by premun** [comment]
I changed it here:
image

**Pull request merged**
