### PR TITLE
Move to GitHub authentication

### PR DESCRIPTION
**Pull request by ChadNedzlek**
Grafana GitHub authentication has more fine grained authorization controls;
in particular, it allows restricting to a particular organization or team, rather than
every entity in the Microsoft AD tenant

### CODE REVIEW

**Comment by garath** [comment]
The failed login page is not very friendly. It's just an error message saying "login.OAuthLogin(missing saved state)". And with the login page also very generic, the new user experience is awkward. Did you happen to notice a reasonable place in the source to customize these pages?

**Comment by ChadNedzlek** [comment]
How did you get a login to fail?  You mean with an account not in the correct org? Or something else?  I don't want to spend a ton of time fixing bugs in grafana unless they are absolute ship stopper.

**Comment by garath** [comment]
I used a second GitHub account I own that is not a member of the dotnet organization.

I played a bit more and discovered that after the rejected login, trying to login from the front page gives a more useful error message about not being in the correct group. But, it's not easy or obvious to get to that path nor does it give practical information on what to do. 

It's debatable that this is a bug. Grafana correctly did not allow my unauthorized user to log in. More it's just a poor user experience. Given @Chrisboh's concern in this area we should consider make sure these cases are acceptable.

**Comment by ChadNedzlek** [comment]
@Chrisboh Thoughts?

I _think_ all the people we want looking at this are already in the dotnet org, so no one we care about should be encountering this. But if there is someone I missed or someone new, it's not a super clear path for them to get to success

Though I'm not sure what would be better... leaking the information of the correct team/org to an unauthorized person isn't acceptable, and I doubt the AAD solution would be any better. The error message is... a bit overly technical... but at best it would become something vague of "403 Unauthorized", which isn't _much_ better.

In general, when someone is unauthorized, most applications will tell them nothing, because telling them _anything_ leaks data to them about attack vectors.  Like when you have a bad SAS token to a blob, it doesn't tell you who the owner is.  I don't think grafana is unique in this regard.

**Comment by ChadNedzlek** [comment]
This might be a totally different problem... let me check. This might be related to https://github.com/grafana/grafana/issues/5823.

**Comment by garath** [comment]
I just retried and saw different behavior. This time it redirected me nicely to the login screen with an error flyover that said I wasn't in the right org. This is nicer behavior. Did you change something?

**Comment by ChadNedzlek** [comment]
Nope.  Hrm. I wonder what happened. I saw that weird state message too when I rebooted the server in the middle and I had to log in again.  It's possible we have some weird bug because we are running a pretty random commit from master.

**Comment by garath** [comment]
I've tried to repro but cannot. So, hopefully this was a rare transient error.

**Comment by garath** [comment]
I'm okay with this behavior. It signals enough to a user that "the process worked, you just aren't authorized". Though I do wish our support email address could go on there somewhere.

**Comment by Chrisboh** [comment]
I agree with you Chad that I think we are fine considering we are already using existing groups that should have most people already on them.

**Pull request merged**
