### PR TITLE
Consider skipped checks as meeting Maestro policy

### PR DESCRIPTION
**Pull request by mmitche**
### Release Note Category
- [x] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

### Release Note Description
Consider skipped checks as meeting Maestro policy

### CODE REVIEW

**Comment by premun** [comment]
@mmitche see my comment in Teams about ignored checks and then merge this if you still feel like we should do this

**Comment by oleksandr-didyk** [comment]
Rolled-out by https://github.com/dotnet/arcade-services/pull/3972

**Comment by mmitche** [comment]
This doesn't appear to have worked as expected:

https://github.com/dotnet/sdk/pull/43972

image

**Comment by mmitche** [comment]
It may be that the check is actually neutral and not skipped

**Comment by premun** [comment]
I guess we need to check the GitHub API response to see what is the actual value it returns

**Comment by premun** [comment]
@mmitche are we worried that `Neutral` is also the state before we queue the check? I remember some worries like that so that the service does not merge stuff right away (though we do the 5 minute delay I believe after opening a PR now)

**Comment by premun** [comment]
https://github.com/dotnet/arcade-services/pull/4026

**Comment by akoeplinger** [comment]
Last time we did try to change the neutral state: https://github.com/dotnet/arcade-services/pull/2997

**Comment by marcpopMSFT** [comment]
Any more news here? Still affecting SDK PR checks.

**Comment by nagilson** [comment]
Any updates here? Thanks for investigating.

**Pull request merged**
