### PR TITLE
Migrate RolloutScorer to Azure.Security.KeyVault

### PR DESCRIPTION
**Pull request by dkurepa**
Part of https://github.com/dotnet/arcade/issues/11756
We split things for easier validation

### CODE REVIEW

**Comment by missymessa** [comment]
@jonfortescue is it possible to test RolloutScorer on staging?

**Comment by jonfortescue** [comment]
@missymessa rollout scorer can be tested locally (both the CLI and the function) and does in fact have a staging instance (rolloutscorer-staging).

@dkurepa thanks so much for doing this!!

**Review by jonfortescue — APPROVED** [review]

**Comment by missymessa** [comment]
@jonfortescue, thanks! Djuradj said he tested it locally and it was fine, I think he wanted to just make sure it would run on staging after he merged his PR, so he might need some guidance on that (he probably already reached out to you, though :) )

**Comment by dkurepa** [comment]
> Love it.
> 
> There are some places here that could adopt MSI but that's probably out of scope for this PR.

Definitely! I will be creating a DotNet.Status PR next to test out the changes you made on your branch!

**Pull request merged**
