### PR TITLE
Alerts when autoscaler stopped running

### PR DESCRIPTION
**Pull request by AlitzelMendez**

### CODE REVIEW

**Comment by garath** [comment]
What's the thinking behind this particular alert level? Can you point me to some times where autoscale went down and this alert would have triggered?

**Comment by AlitzelMendez** [comment]
sure, we have an issue for how to recover after this fails https://github.com/dotnet/core-eng/issues/10298 in that issue we haven been linking most of the times that the autoscaler has stopped

**Comment by garath** [comment]
I looked at this alert against the data from Sept 24, and it doesn't look to me like it would fire. Is that what you expect? It's just not clear to me how effective this alert would be, based on past data. Am I missing something?

**Review by garath — APPROVED** [review]
Spoke with Ali offline. Zero messages does indicate a type of failure that the autoscale team is chasing down, so this does provide a net improvement in monitoring. Ali pointed me to this [panel and time frame](https://dotnet-eng-grafana.westus2.cloudapp.azure.com/d/Gb_PPXlWk/waitingtimemetricstest?orgId=1&from=1602258311414&to=1602269111414) as an example.

Note that the Grafana feature to alert when no data is returned is important here.

**Pull request merged**
