### PR TITLE
Include locations

### PR DESCRIPTION
**Pull request by mmitche**

### CODE REVIEW

**Comment by mmitche** [comment]
Fixes https://github.com/dotnet/arcade/issues/1790

**Comment by alexperovich** [comment]
@mmitche The intention was if locations are desired you need to use the assets api, not the builds api. i.e. "Give me all assets with this buildId, and the locations"

I'm okay merging this but I think this will make the builds api return way more data than is required for most uses. What part of the system needs these?

**Comment by mmitche** [comment]
@alexperovich Gathering drops.  We can hold off on this until it becomes clear this is more efficient than doing two separate queries.

**Comment by alexperovich** [comment]
Yea, if 2 requests is too slow we can revisit this, but the locations data is very large and I don't think it is necessary for most uses of the build api.

**Comment by mmitche** [comment]
Closing this unless needed.

**Pull request closed without merging**
