### PR TITLE
Specify building architecture

### PR DESCRIPTION
**Pull request by dkurepa**
Attempts to fix: https://github.com/dotnet/arcade/issues/12985 by building for x64 instead of `Any CPU`

### CODE REVIEW

**Comment by dkurepa** [comment]
@riarenas could I get your opinion on this please? Recently, our builds have been flaky with [these](https://dev.azure.com/dnceng/internal/_build/results?buildId=2144805&view=results) errors, think this might help

**Comment by riarenas** [comment]
Should we try to bump to the latest release?  I don't see any repositories in the dotnet organization that are specifying this parameter, which makes me think this is a non-standard way of dealing with this situation.

**Comment by garath** [comment]
Won't setting the architecture here cause the same problem for downstream consumers of these libraries? 

Without any other info I would have guessed that this is happening because some library related to Service Fabric (which IIRC must be built as x64 instead of Any CPU) got added as a dependency to another "Any CPU" project. Any chance that's happened recently?

**Comment by dkurepa** [comment]
I had another look at the logs, the only project that was causing the errors was `CoreHealthMonitor.Tests`, so I gave it the `win7-x64` RuntimeIdentifier. This is a test project so it won't get consumed by anything else, and we're already doing the same thing for other test projects

**Review by garath — APPROVED** [review]

**Pull request merged**
