### PR TITLE
Production rollout

### PR DESCRIPTION
**Pull request by riarenas**
Prepping the PR for deployment tomorrow. Please take a look at your changes to make sure everything looks right.

(this will include https://github.com/dotnet/arcade-services/pull/723 when it gets merged)

### CODE REVIEW

**Comment by chcosta** [comment]
@mmitche, maestro-int is failing because of https://github.com/dotnet/arcade-services/commit/56d87235d793e894eb5ea9a6dc43535610ac9338.

The int database has the added "Released" column in builds.  prod database does not.  Web page is failing in the Builds controller with `"Invalid column name 'Released"` which is causing the "Unable to load content" message seen on maestro-int (and my local builds now).

**Comment by chcosta** [comment]
maestro-int is also broken by https://github.com/dotnet/arcade-services/commit/719b4532e5220cc9553b09e6687d702b5521f338 for the same category of reason.  "TimeToInclusionInMinutes" column of "BuildDependencies" table is not available in prod.

**Comment by ChadNedzlek** [comment]
Doesn't the deployment create the tables and schema for all our deployments now? It's driven by entity framework.  The deployment will create those things in prod. @alexperovich can correct me if I'm wrong.

**Comment by riarenas** [comment]
Kind of makes sense:
* The Int BarViz is set to look at prod data (because we have 0 meaningful data in Int) 
* This set of changes includes 3 migrations that modify the DB, and one new API.
* BarViz Int won't work until we roll out to prod because those migrations and the new API won't be available until we roll out.

Looks like something we should look into fixing, because it means BarViz staging doesn't let people test their changes if any database / API changes happen.

**Comment by alexperovich** [comment]
Its not actually int hitting the prod database directly, so the issue isn't SQL schema changes. The int website uses the prod swagger api, and the "repositories" api is 404ing because it doesn't exist in prod.

**Pull request merged**
