### PR TITLE
Update/Remove packages that use Microsoft.Azure.KeyVault

### PR DESCRIPTION
**Pull request by dkurepa**
I chose this version of Kusto.Ingest because it didn't have Microsoft.Azure.KeyVault in it's dependency tree and it didn't update any other packages. Choosing a higher version would have required some major version updating of packages like Newtonsoft.Json and many others.

https://github.com/dotnet/arcade/issues/11852

### CODE REVIEW

**Comment by riarenas** [comment]
> src\Shared\Microsoft.DotNet.Kusto\KustoHelpers.cs(97,44): error CS0618: (NETCORE_ENGINEERING_TELEMETRY=Build) 'CsvColumnMapping' is obsolete: 'This class is obsolete. Please use Kusto.Data.Common.ColumnMapping instead'

Looks like there are some changes that need to happen to the code to account for the new bump in major version.

Trying to understand the situation. Is the problem that the current version has a dependency on the package that we can't reference anymore, and this is the first version that removed that dependency and therefore we think it's the upgrade that will require the least additional changes?

How much work is it to update to the latest package? If we have to move major versions anyways, should we consider moving to the latest stable?

**Comment by dkurepa** [comment]
> > src\Shared\Microsoft.DotNet.Kusto\KustoHelpers.cs(97,44): error CS0618: (NETCORE_ENGINEERING_TELEMETRY=Build) 'CsvColumnMapping' is obsolete: 'This class is obsolete. Please use Kusto.Data.Common.ColumnMapping instead'
> 
> Looks like there are some changes that need to happen to the code to account for the new bump in major version.
> 
> Trying to understand the situation. Is the problem that the current version has a dependency on the package that we can't reference anymore, and this is the first version that removed that dependency and therefore we think it's the upgrade that will require the least additional changes?
> 
> How much work is it to update to the latest package? If we have to move major versions anyways, should we consider moving to the latest stable?

Yup, these were not showing up on my local machine.

Yes, we can't use the `Kusto.Ingest` version `8.1.0` anymore, I thought this would be a quick and easy fix, but I was wrong. If it will be a similar amount of work to update to the latest stable version, then I agree we should do it

**Comment by dkurepa** [comment]
It should be pretty easy to verify the Kusto changes once they're in staging

**Comment by riarenas** [comment]
I either remember / dreamt there was some effort (and possibly fallout?) from updating Kusto libraries in helix-service. Paging @missymessa @ChadNedzlek and @AlitzelMendez in case this rings any bells or there are any concerns with these kusto library changes.

**Comment by ChadNedzlek** [comment]
My brain says the following:

There was a breaking change to how they handled connection strings, and no connection string would work in both places.  One of the values was required by one of the libraries, and rejected by the other.  Assuming they don’t do anything crazy like that again, it should be fine.

**Comment by ChadNedzlek** [comment]
Now that I read the thread it sounds like they just really like making breaking changes, and given the experience last time and this one, it sounds like it's going to be a giant mess. :-(

**Comment by garath** [comment]
Helix-service is using the same version of the Kusto libraries as here. In fact, @ChadNedzlek, won't the package synchronize tool cause the helix-service build to break if these versions are updated?

**Comment by ChadNedzlek** [comment]
Correct. All of the corresponding changes will need to be made in Helix as well during the next dependency flow. If we know this is a significant one that will involve code changes (like it sounds like it is), we should do that as part of this work and not leave it as a sneaky surprise for the next person that attempts to get a change from arcade-services.

**Comment by dkurepa** [comment]
Based on https://dev.azure.com/dnceng/internal/_componentGovernance/dotnet-arcade-services/alert/7526527?typeId=5149674, we have to update this package to a higher version. Think we'll eventually have to do it in helix service too https://dev.azure.com/dnceng/internal/_componentGovernance/dotnet-helix-service/alert/7523787?typeId=10986844&pipelinesTrackingFilter=1.


> My brain says the following:
> 
> There was a breaking change to how they handled connection strings, and no connection string would work in both places. One of the values was required by one of the libraries, and rejected by the other. Assuming they don’t do anything crazy like that again, it should be fine.

I'm not sure I follow, are you saying this PR will break things because of the changes with these connection string as it is?

**Comment by ChadNedzlek** [comment]
I was filling in @riarenas mention of me. That was the drama last time.  Last time, they pretty badly broke how connection strings were handled, that was the difficulty. This package is notorious for surprising breaking changes, many of which only appear at runtime (when it attempts to use the connection string from the staging/production vault to connect to the cluster).

**Comment by dkurepa** [comment]
In that case, if something is wrong, we will see it in staging. We are running the Telemetry app there should it should be pretty clear if we hit some new errors like this. Thanks for the info!

**Review by riarenas — APPROVED** [review]

**Comment by dkurepa** [comment]
I think this change broke Staging Kusto, TimelineBuilds hasn't gotten an update since this was rolled out to staging, will revert

**Pull request merged**
