### PR TITLE
Swtich to using the Preview LangVersion?

### PR DESCRIPTION
**Pull request by JohnTortugo**
I'm getting the errors below when building Darc and the monitoring SDK. Am I the only one getting those? This PR address the errors.

```
32>Operations\GatherDropOperation.cs(1173,17,1173,22): error CS8652: The feature 'using declarations' is currently in Preview and *unsupported*. To use Preview features, use the 'preview' language version.
32>Operations\GatherDropOperation.cs(1249,13,1249,18): error CS8652: The feature 'using declarations' is currently in Preview and *unsupported*. To use Preview features, use the 'preview' language version.
32>Operations\GatherDropOperation.cs(1369,17,1369,22): error CS8652: The feature 'using declarations' is currently in Preview and *unsupported*. To use Preview features, use the 'preview' language version.
32>Operations\GatherDropOperation.cs(1370,17,1370,22): error CS8652: The feature 'using declarations' is currently in Preview and *unsupported*. To use Preview features, use the 'preview' language version.
32>Operations\GatherDropOperation.cs(1390,21,1390,26): error CS8652: The feature 'using declarations' is currently in Preview and *unsupported*. To use Preview features, use the 'preview' language version.
32>Operations\GatherDropOperation.cs(1401,21,1401,26): error CS8652: The feature 'using declarations' is currently in Preview and *unsupported*. To use Preview features, use the 'preview' language version.
32>Operations\GatherDropOperation.cs(1173,17,1173,22): error CS8652: The feature 'using declarations' is currently in Preview and *unsupported*. To use Preview features, use the 'preview' language version.
32>Operations\GatherDropOperation.cs(1249,13,1249,18): error CS8652: The feature 'using declarations' is currently in Preview and *unsupported*. To use Preview features, use the 'preview' language version.
32>Operations\GatherDropOperation.cs(1369,17,1369,22): error CS8652: The feature 'using declarations' is currently in Preview and *unsupported*. To use Preview features, use the 'preview' language version.
32>Operations\GatherDropOperation.cs(1370,17,1370,22): error CS8652: The feature 'using declarations' is currently in Preview and *unsupported*. To use Preview features, use the 'preview' language version.
32>Operations\GatherDropOperation.cs(1390,21,1390,26): error CS8652: The feature 'using declarations' is currently in Preview and *unsupported*. To use Preview features, use the 'preview' language version.
32>Operations\GatherDropOperation.cs(1401,21,1401,26): error CS8652: The feature 'using declarations' is currently in Preview and *unsupported*. To use Preview features, use the 'preview' language version.
```

```
14>GrafanaClient.cs(200,20,200,23): error CS8652: The feature 'coalescing assignment' is currently in Preview and *unsupported*. To use Preview features, use the 'preview' language version.
```

### CODE REVIEW

**Comment by riarenas** [comment]
I don't know enough, but moving to a preview version of C# seems like a scary change?

**Comment by mmitche** [comment]
> I don't know enough, but moving to a preview version of C# seems like a scary change?
For critical services? Maybe not a great idea? @jaredpar may have an opinion on this. I think it comes down to how likely issues in the preview versions of C# result in silent bad codegen.

**Comment by JohnTortugo** [comment]
I can just change the code to not use the preview feature.

**Comment by ChadNedzlek** [comment]
Why these 2 assemblies in particular?  I'd rather not have parts of our code bases using different compilers.  If we want to do it, let's just do it.

**Comment by JohnTortugo** [comment]
> Why these 2 assemblies in particular? I'd rather not have parts of our code bases using different compilers. If we want to do it, let's just do it.

If by different compilers you mean different version then we already have a diversity. From a quick look I can see projects using 7.1, 8, latest and default. Getting all to use the same version is another story.

I can change the code to not use the preview feature. Anyone objects?

**Comment by ChadNedzlek** [comment]
Sounds like it would be best not to use the preview features, at least for now, until we can sort out the bevy of compiler versions.

**Comment by jaredpar** [comment]
> I don't know enough, but moving to a preview version of C# seems like a scary change?

Depends on your tolerance level. The way to interpret "preview features" is essentially "high quality beta". Yes we may change the syntax, subtle changes to the semantics, etc ... but the overall story is pretty much in place. For some teams this is acceptable for others this is not. 

> 14>GrafanaClient.cs(200,20,200,23): error CS8652: The feature 'coalescing assignment' is currently in Preview and *unsupported*. To use Preview features, use the 'preview' language version.

This feature shipped in C# 8.0 so it's not preview, it's RTM. Are you using a really old compiler or do you have the `<LangVersion>` MSBuild property set to 7.X?

**Comment by JohnTortugo** [comment]
Both projects where this warning was showing up were configured with `<LangVersion>latest</LangVersion>`. I am building this with VS 2019 16.2 Preview 2.

**Comment by riarenas** [comment]
> I am building this with VS 2019 16.2 Preview 2

I somehow thought you were seeing this in CI. 

Is there a reason why you want to stay in a 16.2 preview when 16.5 is already RTM?

**Comment by JohnTortugo** [comment]
Never mind. Got it working. Thank you all.

**Pull request closed without merging**
